// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furniturefronttest.repository;

import com.katzan.spring.furniturefronttest.model.AboutUs;
import com.katzan.spring.furniturefronttest.repository.AboutUsRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect AboutUsRepository_Roo_Jpa_Repository {
    
    declare parents: AboutUsRepository extends JpaRepository<AboutUs, Long>;
    
    declare parents: AboutUsRepository extends JpaSpecificationExecutor<AboutUs>;
    
    declare @type: AboutUsRepository: @Repository;
    
}
