// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furniturefronttest.model;

import com.katzan.spring.furniturefronttest.model.ImageFileDataOnDemand;
import com.katzan.spring.furniturefronttest.model.ImageFileIntegrationTest;
import com.katzan.spring.furniturefronttest.repository.ImageFileRepository;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ImageFileIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ImageFileIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ImageFileIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ImageFileIntegrationTest: @Transactional;
    
    @Autowired
    ImageFileDataOnDemand ImageFileIntegrationTest.dod;
    
    @Autowired
    ImageFileRepository ImageFileIntegrationTest.imageFileRepository;
    
    @Test
    public void ImageFileIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ImageFile' failed to initialize correctly", dod.getRandomImageFile());
        long count = imageFileRepository.count();
        Assert.assertTrue("Counter for 'ImageFile' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ImageFileIntegrationTest.testFind() {
        ImageFile obj = dod.getRandomImageFile();
        Assert.assertNotNull("Data on demand for 'ImageFile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ImageFile' failed to provide an identifier", id);
        obj = imageFileRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ImageFile' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ImageFile' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ImageFileIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ImageFile' failed to initialize correctly", dod.getRandomImageFile());
        long count = imageFileRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ImageFile', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ImageFile> result = imageFileRepository.findAll();
        Assert.assertNotNull("Find all method for 'ImageFile' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ImageFile' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ImageFileIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ImageFile' failed to initialize correctly", dod.getRandomImageFile());
        long count = imageFileRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ImageFile> result = imageFileRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ImageFile' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ImageFile' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ImageFileIntegrationTest.testFlush() {
        ImageFile obj = dod.getRandomImageFile();
        Assert.assertNotNull("Data on demand for 'ImageFile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ImageFile' failed to provide an identifier", id);
        obj = imageFileRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ImageFile' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyImageFile(obj);
        Integer currentVersion = obj.getVersion();
        imageFileRepository.flush();
        Assert.assertTrue("Version for 'ImageFile' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ImageFileIntegrationTest.testSaveUpdate() {
        ImageFile obj = dod.getRandomImageFile();
        Assert.assertNotNull("Data on demand for 'ImageFile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ImageFile' failed to provide an identifier", id);
        obj = imageFileRepository.findOne(id);
        boolean modified =  dod.modifyImageFile(obj);
        Integer currentVersion = obj.getVersion();
        ImageFile merged = imageFileRepository.save(obj);
        imageFileRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ImageFile' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ImageFileIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ImageFile' failed to initialize correctly", dod.getRandomImageFile());
        ImageFile obj = dod.getNewTransientImageFile(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ImageFile' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ImageFile' identifier to be null", obj.getId());
        imageFileRepository.save(obj);
        imageFileRepository.flush();
        Assert.assertNotNull("Expected 'ImageFile' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ImageFileIntegrationTest.testDelete() {
        ImageFile obj = dod.getRandomImageFile();
        Assert.assertNotNull("Data on demand for 'ImageFile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ImageFile' failed to provide an identifier", id);
        obj = imageFileRepository.findOne(id);
        imageFileRepository.delete(obj);
        imageFileRepository.flush();
        Assert.assertNull("Failed to remove 'ImageFile' with identifier '" + id + "'", imageFileRepository.findOne(id));
    }
    
}
