// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furniturefronttest.model;

import com.katzan.spring.furniturefronttest.model.ImageFile;
import com.katzan.spring.furniturefronttest.model.ImageFileDataOnDemand;
import com.katzan.spring.furniturefronttest.repository.ImageFileRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ImageFileDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ImageFileDataOnDemand: @Component;
    
    private Random ImageFileDataOnDemand.rnd = new SecureRandom();
    
    private List<ImageFile> ImageFileDataOnDemand.data;
    
    @Autowired
    ImageFileRepository ImageFileDataOnDemand.imageFileRepository;
    
    public ImageFile ImageFileDataOnDemand.getNewTransientImageFile(int index) {
        ImageFile obj = new ImageFile();
        setDescription(obj, index);
        setFileName(obj, index);
        setImageName(obj, index);
        setSize(obj, index);
        return obj;
    }
    
    public void ImageFileDataOnDemand.setDescription(ImageFile obj, int index) {
        String description = "description_" + index;
        if (description.length() > 10240) {
            description = description.substring(0, 10240);
        }
        obj.setDescription(description);
    }
    
    public void ImageFileDataOnDemand.setFileName(ImageFile obj, int index) {
        String fileName = "fileName_" + index;
        obj.setFileName(fileName);
    }
    
    public void ImageFileDataOnDemand.setImageName(ImageFile obj, int index) {
        String imageName = "imageName_" + index;
        if (imageName.length() > 20) {
            imageName = imageName.substring(0, 20);
        }
        obj.setImageName(imageName);
    }
    
    public void ImageFileDataOnDemand.setSize(ImageFile obj, int index) {
        Long size = new Integer(index).longValue();
        obj.setSize(size);
    }
    
    public ImageFile ImageFileDataOnDemand.getSpecificImageFile(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ImageFile obj = data.get(index);
        Long id = obj.getId();
        return imageFileRepository.findOne(id);
    }
    
    public ImageFile ImageFileDataOnDemand.getRandomImageFile() {
        init();
        ImageFile obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return imageFileRepository.findOne(id);
    }
    
    public boolean ImageFileDataOnDemand.modifyImageFile(ImageFile obj) {
        return false;
    }
    
    public void ImageFileDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = imageFileRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ImageFile' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ImageFile>();
        for (int i = 0; i < 10; i++) {
            ImageFile obj = getNewTransientImageFile(i);
            try {
                imageFileRepository.save(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            imageFileRepository.flush();
            data.add(obj);
        }
    }
    
}
