// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furniturefronttest.model;

import com.katzan.spring.furniturefronttest.model.AboutUs;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AboutUs_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager AboutUs.entityManager;
    
    public static final EntityManager AboutUs.entityManager() {
        EntityManager em = new AboutUs().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long AboutUs.countAboutUses() {
        return entityManager().createQuery("SELECT COUNT(o) FROM AboutUs o", Long.class).getSingleResult();
    }
    
    public static List<AboutUs> AboutUs.findAllAboutUses() {
        return entityManager().createQuery("SELECT o FROM AboutUs o", AboutUs.class).getResultList();
    }
    
    public static AboutUs AboutUs.findAboutUs(Long id) {
        if (id == null) return null;
        return entityManager().find(AboutUs.class, id);
    }
    
    public static List<AboutUs> AboutUs.findAboutUsEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM AboutUs o", AboutUs.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void AboutUs.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void AboutUs.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            AboutUs attached = AboutUs.findAboutUs(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void AboutUs.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void AboutUs.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public AboutUs AboutUs.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        AboutUs merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
