// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furniturefronttest.model;

import com.katzan.spring.furniturefronttest.model.DocFound;

privileged aspect DocFound_Roo_JavaBean {
    
    public String DocFound.getId() {
        return this.id;
    }
    
    public void DocFound.setId(String id) {
        this.id = id;
    }
    
    public long DocFound.getItem_id() {
        return this.item_id;
    }
    
    public void DocFound.setItem_id(long item_id) {
        this.item_id = item_id;
    }
    
    public String DocFound.getName() {
        return this.name;
    }
    
    public void DocFound.setName(String name) {
        this.name = name;
    }
    
    public String DocFound.getCodeNumber() {
        return this.codeNumber;
    }
    
    public void DocFound.setCodeNumber(String codeNumber) {
        this.codeNumber = codeNumber;
    }
    
    public String DocFound.getDescription() {
        return this.description;
    }
    
    public void DocFound.setDescription(String description) {
        this.description = description;
    }
    
    public String DocFound.getController() {
        return this.controller;
    }
    
    public void DocFound.setController(String controller) {
        this.controller = controller;
    }
    
    public String DocFound.getFoto() {
        return this.foto;
    }
    
    public void DocFound.setFoto(String foto) {
        this.foto = foto;
    }
    
}
