// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furniturefronttest.model;

import com.katzan.spring.furniturefronttest.model.DocFound;
import com.katzan.spring.furniturefronttest.model.SearchResults;
import java.util.Collection;

privileged aspect SearchResults_Roo_JavaBean {
    
    public long SearchResults.getResultsNumber() {
        return this.resultsNumber;
    }
    
    public void SearchResults.setResultsNumber(long resultsNumber) {
        this.resultsNumber = resultsNumber;
    }
    
    public Collection<DocFound> SearchResults.getDocuments() {
        return this.documents;
    }
    
    public void SearchResults.setDocuments(Collection<DocFound> documents) {
        this.documents = documents;
    }
    
}
