// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.katzan.spring.furniturefronttest.model;

import com.katzan.spring.furniturefronttest.model.ServiceItem;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ServiceItem_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager ServiceItem.entityManager;
    
    public static final EntityManager ServiceItem.entityManager() {
        EntityManager em = new ServiceItem().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ServiceItem.countServiceItems() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ServiceItem o", Long.class).getSingleResult();
    }
    
    public static List<ServiceItem> ServiceItem.findAllServiceItems() {
        return entityManager().createQuery("SELECT o FROM ServiceItem o", ServiceItem.class).getResultList();
    }
    
    public static ServiceItem ServiceItem.findServiceItem(Long id) {
        if (id == null) return null;
        return entityManager().find(ServiceItem.class, id);
    }
    
    public static List<ServiceItem> ServiceItem.findServiceItemEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ServiceItem o", ServiceItem.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void ServiceItem.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ServiceItem.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ServiceItem attached = ServiceItem.findServiceItem(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ServiceItem.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ServiceItem.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ServiceItem ServiceItem.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ServiceItem merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
